service: barstool-backend-challenge

provider:
  name: aws
  profile: barstool
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 1024
  timeout: 30
  versionFunctions: false
  stage: dev

package:
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    allowCache: true

plugins:
  - serverless-offline

functions:
  proxy:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{path+}
          method: ANY
